### ISSUE TITLE
Check fees for compatibility with 0.54.0

### ISSUE THREAD

**Issue by edd** [vegaprotocol/sample-api-scripts#148]
[vegaprotocol/documentation#165](https://github.com/vegaprotocol/documentation/pull/165) migrated the sample api scripts pages over to the new docs, but they were disabled in [vegaprotocol/documentation#181](https://github.com/vegaprotocol/documentation/pull/181) because some were found to be incompatible with 0.53.0. As 0.54.0 is soon-to-be-tagged, let’s check for compatibility with that version/`develop`, and either decide to rewrite the script, or re-enable. 

# Tasks
- [ ] Check if all scripts in this folder (Python, Shell, etc) work with 0.54.0
- [ ] Fix any minor incompatibilities
- [ ] Create a follow up task to rewrite it, or delete it

**Comment by cdm** [comment]
Closed, superceded by work in #163
