### ISSUE TITLE
Fix python proposal sample scripts and add freeform governance

### ISSUE THREAD

**Issue by wwestgarth** [vegaprotocol/sample-api-scripts#93]
The python sample scripts for proposing a market and updating network-parameters are both out of date due to breaking changes in core. They should be updated so that they continue to work.

Also a new proposal type, freeform, has been added to core. An example for this should be added too.

# Tasks
- [ ] Fix `propose-vote-enact-market.py`
- [ ] Fix `propose-vote-enact-netparams.py`
- [ ] Add example for freeform goverance proposal
